# Treatment / management knowledge base -- content from notebook Cell 11.1 (only "--" shown as an em dash).
# =============================================================================
# CELL: treatment_recommendation_v8_cell.py -- TomatoLeafAI v8 treatment /
# management recommendation module
# =============================================================================
# Self-contained notebook cell. Standard library only (no external deps),
# so it can be pasted into any notebook cell (training notebook, Flask app
# backend, or a standalone inference notebook) with zero imports beyond
# what's already here.
#
# SCOPE / HONESTY NOTE: This module returns agronomic MANAGEMENT guidance,
# not a diagnosis and not a severity grade. Per the thesis proposal's own
# stated limitations, this system does NOT include pixel/heatmap-based
# disease-severity grading -- so `severity_note` says that explicitly on
# every entry rather than inventing a fake severity score. Symptom text
# reflects well-documented, standard plant-pathology facts about these ten
# common PlantVillage tomato classes (general textbook/extension-service
# knowledge), not model output and not fabricated specifics.
# =============================================================================

from __future__ import annotations

from typing import Dict, Optional

# ---------------------------------------------------------------------------
# Fixed disclaimer -- present, verbatim, on EVERY recommendation returned by
# get_treatment_recommendation(), unconditionally (no confidence level, no
# class, no code path skips this).
# ---------------------------------------------------------------------------
DISCLAIMER = (
    "This is decision-support guidance generated by an automated "
    "image-classification system, not a substitute for diagnosis by a "
    "qualified local agronomist or plant pathologist, and not a substitute "
    "for reading and following actual pesticide product labels and local "
    "agricultural-extension guidance before applying any chemical control."
)

# ---------------------------------------------------------------------------
# The exact 10 PlantVillage tomato classes this project targets.
# ---------------------------------------------------------------------------
CLASS_NAMES = [
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]

SEVERITY_DISCLAIMER = (
    "This system classifies disease TYPE from a leaf image only; it does not "
    "quantify how much of the plant/leaf area is affected. Pixel- or "
    "heatmap-based severity grading is explicitly out of scope for this "
    "thesis (see the proposal's stated limitations: 'does not include "
    "grading disease severity'). Treat this output as a presence/absence "
    "call for the listed disease, not a severity score."
)

# =============================================================================
# Structured per-class knowledge base
# =============================================================================

TREATMENT_DATABASE: Dict[str, Dict[str, object]] = {

    "Tomato___Bacterial_spot": {
        "disease_name": "Bacterial Spot",
        "pathogen_type": "bacterial",
        "symptoms_observed": [
            "Small, water-soaked, greasy-looking spots on leaves that turn dark brown to black",
            "Spots often have a yellow halo and may coalesce into larger necrotic patches",
            "Raised, scabby brown lesions can also appear on green fruit",
            "Severe infection causes leaf yellowing and premature defoliation",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Use certified disease-free seed and transplants",
            "Rotate out of tomato/pepper for at least 1-2 years",
            "Increase plant spacing to improve airflow and reduce leaf wetness duration",
            "Avoid working in fields when foliage is wet (spreads bacteria on hands/tools)",
        ],
        "sanitation": [
            "Remove and destroy infected plant debris at season end (do not compost)",
            "Disinfect stakes, cages, and tools between uses",
        ],
        "irrigation_water_management": [
            "Switch to drip/furrow irrigation; avoid overhead sprinklers that splash bacteria onto foliage",
            "Water in the morning so any leaf wetness dries quickly",
        ],
        "monitoring_advice": [
            "Scout weekly, especially after wind-driven rain, which spreads bacterial spot rapidly",
        ],
        "control_category": "chemical_may_be_needed",
        "prevention_advice": [
            "Plant resistant/tolerant cultivars where available",
            "Use copper-based bactericides preventatively in high-pressure regions (copper resistance is documented in some populations, per local extension guidance)",
            "Avoid overhead irrigation and dense planting",
        ],
    },

    "Tomato___Early_blight": {
        "disease_name": "Early Blight",
        "pathogen_type": "fungal",
        "symptoms_observed": [
            "Dark brown lesions with concentric 'target-board' rings, usually starting on older/lower leaves",
            "Yellowing of tissue surrounding the lesions",
            "Can also cause dark, sunken lesions on stems (collar rot) and fruit near the calyx",
            "Progressive lower-canopy defoliation under favorable conditions",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Rotate with non-solanaceous crops for 2-3 years",
            "Stake/cage plants and prune lower leaves to improve airflow",
            "Use resistant or tolerant tomato varieties where available",
            "Mulch to reduce soil splash onto lower leaves",
        ],
        "sanitation": [
            "Remove and destroy infected lower leaves as they appear",
            "Clear and destroy crop debris after harvest (the fungus overwinters in debris)",
        ],
        "irrigation_water_management": [
            "Use drip irrigation instead of overhead watering",
            "Water early in the day so foliage dries before evening",
        ],
        "monitoring_advice": [
            "Scout the lower canopy first, since early blight typically starts there",
            "Increase scouting frequency during warm, humid, or rainy stretches",
        ],
        "control_category": "chemical_may_be_needed",
        "prevention_advice": [
            "Apply protectant fungicides (e.g., chlorothalonil- or mancozeb-based, per label) on a preventive schedule in high-risk periods",
            "Ensure balanced fertility — avoid nitrogen excess/deficiency, both of which increase susceptibility",
            "Improve airflow via spacing and pruning",
        ],
    },

    "Tomato___Late_blight": {
        "disease_name": "Late Blight",
        "pathogen_type": "fungal",
        "symptoms_observed": [
            "Large, irregular, water-soaked greenish-black lesions on leaves that expand rapidly",
            "White, fuzzy fungal growth (sporulation) visible on the underside of lesions in humid conditions",
            "Dark, greasy-looking lesions on stems and firm brown lesions on fruit",
            "Can destroy an entire field within days under cool, wet weather — historically the cause of the Irish potato famine pathogen lineage",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Plant resistant varieties where available (late blight resistance breeding is active)",
            "Avoid planting near or downwind of infected potato fields (shared pathogen, Phytophthora infestans)",
            "Increase plant spacing for airflow",
        ],
        "sanitation": [
            "Destroy infected plants immediately — do not compost; bag or bury deeply",
            "Remove volunteer tomato/potato plants and cull piles that can harbor the pathogen between seasons",
        ],
        "irrigation_water_management": [
            "Avoid overhead irrigation entirely; use drip irrigation",
            "Avoid irrigating in late afternoon/evening — prolonged leaf wetness strongly favors this pathogen",
        ],
        "monitoring_advice": [
            "Treat as a time-critical disease: scout daily during cool, wet weather and act immediately on suspected detections",
            "Monitor regional late blight forecasting/alert networks where available",
        ],
        "control_category": "chemical_may_be_needed",
        "prevention_advice": [
            "Apply preventive fungicides before disease onset in high-risk (cool, wet) weather, per label and local extension advisories",
            "Act fast once detected — late blight can spread through a field in days",
            "Remove and destroy infected plants promptly to reduce inoculum",
        ],
    },

    "Tomato___Leaf_Mold": {
        "disease_name": "Leaf Mold",
        "pathogen_type": "fungal",
        "symptoms_observed": [
            "Pale green to yellow spots on the upper leaf surface with no sharp margins",
            "Olive-green to grayish-purple velvety fungal growth on the corresponding lower leaf surface",
            "Leaves curl, wither, and drop in severe cases",
            "Primarily a problem in greenhouse/high-humidity environments",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Improve greenhouse/field ventilation to reduce humidity around foliage",
            "Increase plant spacing and prune to open the canopy",
            "Use resistant varieties where available (several resistance genes are commercially available)",
        ],
        "sanitation": [
            "Remove and destroy infected leaves promptly",
            "Clear plant debris at the end of the season",
        ],
        "irrigation_water_management": [
            "Avoid overhead watering and misting that keeps foliage and greenhouse air humid",
            "Water early so foliage/air can dry through the day",
        ],
        "monitoring_advice": [
            "In greenhouses, monitor relative humidity; leaf mold thrives above roughly 85% RH",
        ],
        "control_category": "chemical_may_be_needed",
        "prevention_advice": [
            "Lower humidity via ventilation/dehumidification (often more effective than fungicide alone in greenhouses)",
            "Use resistant cultivars",
            "Apply labeled fungicides if cultural controls are insufficient",
        ],
    },

    "Tomato___Septoria_leaf_spot": {
        "disease_name": "Septoria Leaf Spot",
        "pathogen_type": "fungal",
        "symptoms_observed": [
            "Numerous small, circular spots with dark brown margins and tan/gray necrotic centers",
            "Tiny black fungal fruiting bodies (pycnidia) often visible in the center of older spots",
            "Starts on lower/older leaves and moves upward",
            "Heavy infection causes extensive yellowing and defoliation, weakening the plant",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Rotate with non-solanaceous crops for at least 1-2 years",
            "Stake/cage and prune to improve airflow",
            "Mulch to reduce soil splash (the fungus survives in soil debris)",
        ],
        "sanitation": [
            "Remove and destroy infected leaves as soon as spotted",
            "Remove and destroy crop debris after harvest",
        ],
        "irrigation_water_management": [
            "Switch to drip irrigation; avoid overhead watering",
            "Water in the morning so foliage dries quickly",
        ],
        "monitoring_advice": [
            "Scout lower leaves regularly, especially during warm, wet, or humid periods",
        ],
        "control_category": "chemical_may_be_needed",
        "prevention_advice": [
            "Apply protectant fungicides on a preventive schedule during high-risk weather, per label",
            "Remove lower infected leaves promptly to slow upward spread",
            "Avoid working among wet plants to reduce spore spread",
        ],
    },

    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "disease_name": "Two-Spotted Spider Mite Infestation",
        "pathogen_type": "pest",
        "symptoms_observed": [
            "Fine yellow/white stippling (tiny speckled spots) on the upper leaf surface",
            "Fine webbing on the underside of leaves and between stems in heavy infestations",
            "Leaves may bronze, dry out, and drop under sustained feeding pressure",
            "Damage worsens rapidly in hot, dry conditions that favor mite reproduction",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Avoid excess nitrogen fertilization, which can favor mite population growth",
            "Reduce plant drought stress — water-stressed plants are more susceptible",
            "Remove heavily infested leaves/plants to reduce mite load",
        ],
        "sanitation": [
            "Remove weeds and volunteer plants near the field that can host mites between crops",
        ],
        "irrigation_water_management": [
            "Maintain adequate, consistent soil moisture; drought-stressed plants are more vulnerable",
            "Periodic overhead water/hosing of foliage can physically dislodge mites (unlike fungal diseases, this is one case where some overhead water can help, used carefully)",
        ],
        "monitoring_advice": [
            "Inspect leaf undersides with a hand lens regularly, especially in hot/dry weather",
            "Watch for natural predators (predatory mites, ladybird beetles) before applying broad-spectrum pesticides that would also kill them",
        ],
        "control_category": "biological_available",
        "prevention_advice": [
            "Introduce/conserve predatory mites (e.g., Phytoseiulus persimilis) as biological control",
            "Use miticidal soaps/oils as needed, rotating modes of action to avoid resistance",
            "Avoid broad-spectrum insecticides that kill natural mite predators and can trigger outbreaks",
        ],
    },

    "Tomato___Target_Spot": {
        "disease_name": "Target Spot",
        "pathogen_type": "fungal",
        "symptoms_observed": [
            "Circular brown lesions with concentric target-like rings, similar in appearance to early blight",
            "Lesions can appear on leaves, stems, and fruit",
            "Leaf lesions may have a yellow halo and can cause a shot-hole appearance as tissue drops out",
            "Favored by warm, humid conditions and dense canopies",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Rotate with non-host crops",
            "Increase spacing and prune to reduce canopy humidity",
            "Stake plants to keep foliage/fruit off the ground",
        ],
        "sanitation": [
            "Remove and destroy infected leaves and crop debris",
        ],
        "irrigation_water_management": [
            "Use drip irrigation; avoid overhead watering",
            "Water in the morning to allow foliage to dry",
        ],
        "monitoring_advice": [
            "Scout regularly during warm, humid periods since target spot can be confused with early blight — confirm before treating",
        ],
        "control_category": "chemical_may_be_needed",
        "prevention_advice": [
            "Apply labeled fungicides preventively in high-pressure regions/seasons",
            "Improve airflow through spacing and pruning",
            "Rotate fungicide modes of action to manage resistance risk",
        ],
    },

    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "disease_name": "Tomato Yellow Leaf Curl Virus (TYLCV)",
        "pathogen_type": "viral",
        "symptoms_observed": [
            "Pronounced upward curling and cupping of leaflets",
            "Marked yellowing (chlorosis) of leaf margins and interveinal areas",
            "Severe stunting of plant growth, especially when infected young",
            "Reduced flowering and fruit set, often with substantial yield loss",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Plant TYLCV-resistant/tolerant tomato varieties — the single most effective long-term management option",
            "Use reflective mulches (e.g., silver plastic) to repel the whitefly vector",
            "Remove and destroy infected plants promptly to reduce virus reservoir",
        ],
        "sanitation": [
            "Remove nearby weeds that can host whiteflies or the virus between crops",
            "Avoid planting new tomatoes directly next to a recently infected field",
        ],
        "irrigation_water_management": [
            "No direct role in TYLCV management — irrigation practice does not affect a whitefly-vectored virus",
        ],
        "monitoring_advice": [
            "Monitor whitefly (Bemisia tabaci) populations with yellow sticky traps",
            "Scout young transplants closely, since early infection causes the most severe stunting/yield loss",
        ],
        "control_category": "vector_control_for_viral",
        "prevention_advice": [
            "There is no direct chemical cure for a viral infection — management targets the whitefly vector and resistant genetics, not the virus itself",
            "Use insecticides or insect-proof netting/screening to reduce whitefly populations on young plants, per label and local guidance",
            "Prioritize resistant/tolerant cultivars and reflective mulch as the primary defense",
        ],
    },

    "Tomato___Tomato_mosaic_virus": {
        "disease_name": "Tomato Mosaic Virus (ToMV)",
        "pathogen_type": "viral",
        "symptoms_observed": [
            "Light and dark green mottled/mosaic pattern on leaves",
            "Leaf distortion — narrowing, curling, or fern-like leaflet shapes",
            "Stunted plant growth and internal browning of fruit in severe cases",
            "Can be spread mechanically (hands, tools, tobacco products) as well as through seed",
        ],
        "severity_note": SEVERITY_DISCLAIMER,
        "cultural_practices": [
            "Use certified virus-free seed and resistant varieties (Tm resistance genes are widely available)",
            "Rotate out of tomato for at least 1 year in infected fields",
            "Avoid handling plants after using tobacco products, since ToMV/TMV can be present in cured tobacco",
        ],
        "sanitation": [
            "Wash hands and disinfect tools (e.g., with a dilute bleach or trisodium phosphate solution) between handling plants",
            "Remove and destroy infected plants — do not compost",
        ],
        "irrigation_water_management": [
            "No direct role in ToMV management — this virus spreads mechanically/by contact, not primarily through irrigation water",
        ],
        "monitoring_advice": [
            "Scout for mosaic mottling and leaf distortion, especially after handling multiple plants in succession",
        ],
        "control_category": "vector_control_for_viral",
        "prevention_advice": [
            "There is no direct chemical cure for a viral infection — prevention relies on sanitation, resistant varieties, and clean seed/transplants",
            "Minimize plant-to-plant handling and disinfect tools between plants",
            "Remove and destroy infected plants promptly to limit mechanical spread",
        ],
    },

    "Tomato___healthy": {
        "disease_name": "Healthy Plant",
        "pathogen_type": "none",
        "symptoms_observed": [
            "No disease symptoms detected in the analyzed leaf image",
            "Uniform green coloration and normal leaf shape/turgor expected of a healthy plant",
        ],
        "severity_note": (
            "Not applicable — no disease was detected in this image. Note this "
            "reflects the single analyzed leaf/image only, not a whole-plant or "
            "whole-field health guarantee."
        ),
        "cultural_practices": [
            "Continue crop rotation planning (avoid consecutive tomato/solanaceous seasons in the same soil)",
            "Maintain adequate plant spacing and staking/pruning for airflow",
            "Use balanced fertilization based on soil testing rather than guesswork",
        ],
        "sanitation": [
            "Keep removing any fallen leaves/fruit debris around the base of plants",
            "Sanitize tools periodically as routine good practice",
        ],
        "irrigation_water_management": [
            "Prefer drip/soil-level irrigation and water in the morning as routine good practice",
        ],
        "monitoring_advice": [
            "Continue routine weekly scouting so any future disease onset is caught early",
        ],
        "control_category": "none_healthy",
        "prevention_advice": [
            "Maintain current good cultural, sanitation, and irrigation practices",
            "Rotate resistant varieties into future plantings as a proactive measure",
            "Keep monitoring regularly even though no disease is currently detected",
        ],
    },
}

assert set(TREATMENT_DATABASE.keys()) == set(CLASS_NAMES), "Treatment DB must cover exactly the 10 target classes"


# =============================================================================
# Public API
# =============================================================================

def _advisory_level(
    confidence: float,
    high_threshold: float = 0.85,
    moderate_threshold: float = 0.60,
) -> str:
    """Maps a confidence score in [0, 1] to an advisory level. Thresholds
    are configurable via the keyword args (defaults: >=0.85 high, >=0.60
    moderate, below that low)."""
    if confidence >= high_threshold:
        return "high_confidence_guidance"
    if confidence >= moderate_threshold:
        return "moderate_confidence_review_recommended"
    return "low_confidence_seek_expert_opinion"


def get_treatment_recommendation(
    predicted_class: str,
    confidence: float,
    calibrated: bool = True,
    high_threshold: float = 0.85,
    moderate_threshold: float = 0.60,
) -> Dict[str, object]:
    """
    Returns the structured treatment/management entry for `predicted_class`,
    augmented with:
      - 'predicted_class', 'confidence', 'calibrated' (echoed inputs)
      - 'advisory_level': one of "high_confidence_guidance" /
        "moderate_confidence_review_recommended" /
        "low_confidence_seek_expert_opinion", derived from `confidence`
        against `high_threshold` / `moderate_threshold` (configurable)
      - 'disclaimer': the fixed DISCLAIMER string, present unconditionally.

    Raises KeyError with a clear message if `predicted_class` is not one of
    the 10 supported classes, and ValueError if confidence is outside
    [0, 1] -- fail loudly rather than silently returning a nonsense
    advisory level.
    """
    if predicted_class not in TREATMENT_DATABASE:
        raise KeyError(
            f"Unknown class '{predicted_class}'. Supported classes: {CLASS_NAMES}"
        )
    if not (0.0 <= confidence <= 1.0):
        raise ValueError(f"confidence must be in [0, 1], got {confidence}")

    entry = dict(TREATMENT_DATABASE[predicted_class])  # shallow copy, don't mutate the DB
    entry["predicted_class"] = predicted_class
    entry["confidence"] = float(confidence)
    entry["calibrated"] = bool(calibrated)
    entry["advisory_level"] = _advisory_level(confidence, high_threshold, moderate_threshold)
    entry["disclaimer"] = DISCLAIMER
    if not calibrated:
        entry["calibration_note"] = (
            "confidence was NOT produced by a calibrated model (e.g. raw "
            "softmax without temperature scaling) — treat the confidence "
            "value, and therefore this advisory_level, as less reliable "
            "than it would be under a calibrated model."
        )
    return entry


